### ISSUE TITLE
If statements coerces objects to boolean 

### ISSUE THREAD

**Issue by samuelcolvin** [noahmorrison/chevron#17]
Best described by example:

In js:

```js
var Mustache = require('mustache')

var body = '{{#foobar}}\n' +
           '  {{#link}}\n' +
           '  <a href="{{{ link }}}">{{ text}}</a>\n' +
           '  {{/link}}\n' +
           '  {{^link}}\n' +
           '  {{ . }}\n' +
           '  {{/link}}\n' +
           '{{/foobar}}';

var values = [
    'foo',
    'bar',
    {'link': '/', 'text': 'link test'},
    {'link': '/x', 'text': 'x'},
    'spam'
]
```

console.log(Mustache.render(body, {'foobar': values}))
```
  foo
  bar
  <a href="/">link test</a>
  <a href="/x">x</a>
  spam
```

In python using pystache and chevron:
```python
import pystache
import chevron

body = """
{{#foobar}}
  {{#link}}
  <a href="{{{ link }}}">{{ text}}</a>
  {{/link}}
  {{^link}}
  {{ . }}
  {{/link}}
{{/foobar}}
"""

values = [
    'foo',
    'bar',
    {'link': '/', 'text': 'link test'},
    {'link': '/x', 'text': 'x'},
    'spam'
]

print('pystache:')
print(pystache.render(body, {'foobar': values}))

print('chevron:')
print(chevron.render(body, {'foobar': values}))
```

Output:
```
pystache:

  foo
  bar
  <a href="/">link test</a>
  <a href="/x">x</a>
  spam

chevron:

  True
  True
  <a href="/">link test</a>
  <a href="/x">x</a>
  True
```

The values of the list are displayed as bools if the if statement `{{#link}}` is included. Obviously, without that the values display properly.

I've no idea what the spec says about this but I think chrevon should behave the same as mustache.js.

**Comment by noahmorrison** [comment]
This doesn't appear to be in the [spec](https://github.com/mustache/spec), but I do agree that chevron handles it wrong. Luckily it's a simple fix :) I haven't pushed this up to pip yet (Maybe tomorrow, but it's been a long time since I've touched this project and honestly I've forgotten how to push it up to pip :P ), but master works as you want it to.

**Comment by samuelcolvin** [comment]
Great, thanks. Really impressed by the quick response given how long since this was in active development.

On pip deploy, can I suggest add it to travis? See [here](https://github.com/samuelcolvin/pydantic/blob/master/.travis.yml) for an example. It's pretty simple to setup (you just need to encrypt your password and add a section to `.travis.yml`) and once done you can deploy by simply creating a release in github.

(Also master seems to be failing)

**Comment by noahmorrison** [comment]
Hey that's cool! I got it all setup so it's pushing up to pypi now. I also fixed the travis build. Thanks for showing me that!
