### ISSUE TITLE
List rendering is overly restrictive

### ISSUE THREAD

**Issue by gber** [noahmorrison/chevron#33]
Currently rendering of lists is very restrictive as it only accepts python's built-in `list` type.  IMHO that is not pythonic since it does not allow for duck typing or even subclasses of `list`.  This causes problems for me when I pass YAML data parsed by ruamel.yaml into it which uses list-like types for YAML lists.  AFAICS it should not be a problem to check for any iterable type (except a `str` in python3) instead and then loop over it.

**Comment by bugadani** [comment]
I still have an issue with this one since I work with some types (like dict key or value views) that I have to cast to list before passing to render.

**Comment by noahmorrison** [comment]
Would you mind opening a new issue with a specific example of the bad behavior?
