### ISSUE TITLE
Accessing nth element of array

### ISSUE THREAD

**Issue by alanyee** [noahmorrison/chevron#52]
The feature is present in other language implementations of mustache like JS, but it does not seem in this one.

Ideally, we can get something like
```
>>> chevron.render('Hello, {{ mustache.0 }}!', {'mustache': ['World']})
'Hello, World!'
```

**Comment by noahmorrison** [comment]
Dan managed to implement this  before I even saw it :stuck_out_tongue:

This seems useful, kinda weird it's not part of the spec. It's already on master, I'll push a new PyPi version this weekend.

**Comment by jeffbryner** [comment]
Any chance @noahmorrison  this could get pushed to a release? pypi version doesn't have this feature and it would be handy!
