### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jeffbryner** [noahmorrison/chevron#65]
Been awhile since a release and pypi folks doing pip install are missing out on things like issue #52. 

Mind spinning up a release?

**Comment by kiancross** [comment]
Would also appreciate a new pypi release - missing out on #48.

**Comment by mistercrunch** [comment]
+1, happy to help maintaining the package if needed!

**Comment by noahmorrison** [comment]
[0.14.0](https://pypi.org/project/chevron/0.14.0/) has been released. So sorry for the delay!

**Comment by jeffbryner** [comment]
Thanks much! Best part of 2021 so far!
