### ISSUE TITLE
Syntax warning over comparison of literals using is

### ISSUE THREAD

**Issue by tirkarthi** [noahmorrison/chevron#66]
```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./chevron/renderer.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if scope is 0:  # noqa: F632
```

**Comment by mrichman** [comment]
I still get this warning using 0.13.1: `/var/task/chevron/renderer.py:73: SyntaxWarning: "is" with a literal. Did you mean "=="?`

**Comment by noahmorrison** [comment]
The fix has been merged in the [latest version](https://pypi.org/project/chevron/0.14.0/)
