### ISSUE TITLE
Warn on undefined expressions

### ISSUE THREAD

**Issue by joshhansen** [noahmorrison/chevron#71]
Maybe this defies the Mustache spec, but I wish I could get a warning (or error) if I ever try to do {{variable}} for a variable or expression that doesn't exist at all in the data. I'd be happy to try to add such a thing myself but thought I'd see what the author's guidance might be.

**Comment by joshhansen** [comment]
Here's a branch trying to implement this, not yet tested: https://github.com/joshhansen/chevron/tree/master_warn

**Comment by jackgerrits** [comment]
+1 this would be helpful!

**Comment by noahmorrison** [comment]
I've merged your PR into main and pushed it out in the [0.14.0](https://pypi.org/project/chevron/0.14.0/) release of chevron. Thanks for contributing!
