### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by mrichman** [noahmorrison/chevron#75]
I get this warning using 0.13.1: `/var/task/chevron/renderer.py:73: SyntaxWarning: "is" with a literal. Did you mean "=="? if scope is 0:`

**Comment by davepeck** [comment]
I see this too. But the [line of code in question](https://github.com/noahmorrison/chevron/blob/master/chevron/renderer.py#L78) has a `# noqa: F632` which I _think_ should silence the issue. Hrm.

**Comment by tim-pugh** [comment]
@davepeck can you peek at #70 ? Think that may fix the issue, but hasn't been merged.

There is another codebase were we pull this in as a dependency and lock the version, so I'm hopeful if we can get this pulled into the master branch I can raise a PR on that repo.

**Comment by noahmorrison** [comment]
This is merged into the main branch now. Will try to publish a v0.14.0 to pypi today
