### ISSUE TITLE
Disable HTML escaping?

### ISSUE THREAD

**Issue by gaetgu** [noahmorrison/chevron#79]
I have a project in which I am creating an html file with templates. I have done this with handlebars in the past, but I wanted to use chevron this time since it seems to be really easy to use. However, whenever I use any html tags (like \<h1> etc.), it escapes them (like to \&lt;h1\&gt;) 

I know this is not the kind of thing that I should file an issue for, but I couldn't find any sort of discord, slack etc., so this is the only place I know where to ask. If there is such a forum, can someone please direct me to it? Thanks!

**Comment by mistercrunch** [comment]
Similarly I'm considering this library to template/parameterize SQL code provided by users in a safer-than-jinja2 space, and I do not want to html-escape the SQL

**Comment by dcmoore-gd** [comment]
Use `{{{ ... }}}` instead of `{{ ... }}`.
