### ISSUE TITLE
OFFERING HELP MAINTAINING THIS LIBRARY

### ISSUE THREAD

**Issue by mistercrunch** [noahmorrison/chevron#82]
@noahmorrison ! I'd like to offer you help maintaining this library.

I'm the original creator of [Apache Superset](https://superset.apache.org) and [Apache Airflow](https://airflow.apache.org), and currently looking to use `chevron`  in Superset as a safer alternative to Jinja2, which really should be trusted to process user-generated template.

My intent is to merge some of the open PRs that make sense and to publish new versions to PyPI periodically.

It could be as simple as giving me write or admin access to this repo and to PyPI (same username: `mistercrunch` there) and trusting me with things, or you can define a set of rules that I will happy abiding by.

I'm really hoping we can just push this forward, and hate having to fork, and pip install from our GitHub or another PyPI name.

**Comment by dcmoore-gd** [comment]
I'd be happy to help review PRs!

**Comment by alanyee** [comment]
I would also like to help in maintaining this library.

**Comment by noahmorrison** [comment]
Hey everyone,

Maintaining this library is definitely something that has fallen much lower on my priority list than I, or probably anyone else reading this, wanted it to.

I'd love to start working on getting this library at least one other person who can make sure it doesn't stagnate like this when I'm not active.

I'm not even sure what exactly needs to be done at this point so any and all help as to what I should be doing would be greatly appreciated. I'll start trying to pull in PRs and figure out multi-maintainership for GitHub and PyPi.

Thanks everyone for your support, I love that this project still seems to have some life behind it 🙂

@mistercrunch @dcmoore-gd @alanyee

**Comment by mistercrunch** [comment]
Awesome @noahmorrison , on our side we decided to push forward and secure jinja in our project, so I'm probably not the best person to help. But I'd encourage you to ask for help and give write access to people that have a track record and are offering help.

**Comment by binokkio** [comment]
I'd be happy to help too! Big fan of mustache in general and chevron in particular. If you need any more reviewers sign me up :).

**Comment by alanyee** [comment]
I would say that this library is mostly in maintenance mode. I believe everything is up to [spec](https://github.com/mustache/spec) especially since the spec itself has not been updated in some time, so there is no need for a roadmap. It's more or less experimenting and adding in features users ask for, may want, and make sense that are not part of the spec, and making sure the library stays inline with non-deprecated libraries and maintained Python versions. As a trivial example, for instance, latest versions of Python raises a `SyntaxWarning` on https://github.com/noahmorrison/chevron/blob/78f1a384eddef16906732d8db66deea6d37049b7/chevron/renderer.py#L78 Given the `noqa` to suppress existing warnings, it would make sense to suppress the native `SyntaxWarning` as well. If you need help, I am willing to help. Personally, the first thing to do is bring back up the automated tests.

**Comment by dcmoore-gd** [comment]
BTW I've seen several Django packages that have gotten to this point (established, original maintainer has less time) be absorbed into the [JazzBand](https://github.com/jazzband) project successfully.

**Comment by xavivars** [comment]
I'd ➕ trying to move this to [JazzBand](https://github.com/jazzband). I was looking for this feature earlier, and found it had been merged more than a year ago, but there are no releases that include it (another user already pointied it out) https://github.com/noahmorrison/chevron/pull/94#issuecomment-1153677180

**Comment by dbohdan** [comment]
@noahmorrison Could you invite @mistercrunch or another person as a committer to this repository? They could start merging PRs and resolving issues. Inviting a contributor only takes a minute in the settings and is reversible. If something goes wrong, you can revoke their access. Contributor access also doesn't equal administrative access to the repository: they can't rename or delete the repository, can't invite others, etc.

**Comment by Remi-Gau** [comment]
I'd be happy to help with maintenance and go through the backlog of issues and PRs.

**Comment by Remi-Gau** [comment]
FYI I will probably start pushing a "chevron_plus" to pypi to implement new features and fixes to chevron, until this repo is brought back online.

**Comment by dannysauer** [comment]
https://pypi.org/project/chevron-blue/ looks like the "most maintained" fork, so it's what I'm using. :shrug:

**Comment by mistercrunch** [comment]
I'm retracting my offer to help as we went another way, but seems https://pypi.org/project/chevron-blue/ is the way to go. Closing this one since not relevant anymore.
