### ISSUE TITLE
[Feature Request] Ability to disable loading partials from the filesystem

### ISSUE THREAD

**Issue by alanyee** [noahmorrison/chevron#84]
Interesting point raised in https://github.com/apache/incubator-superset/pull/11617

Developers should be able to turn off potentially unsafe features — in this case, loading in partials — if they do not plan to use them.

**Comment by noahmorrison** [comment]
Does [this commit](https://github.com/noahmorrison/chevron/commit/784bbb71761ac097573fd94a3416dda4e01d4202) close this issue for you?

**Comment by alanyee** [comment]
LGTM 👍
