### ISSUE TITLE
Add option for skipping escaping

### ISSUE THREAD

**Issue by bsergean** [noahmorrison/chevron#92]
Hi there,

I tried using chevron this morning but I couldn't find a way to prevent escaping of some string. I am trying to generate C++ with double quotes, and those gets escaped to html &...; which I don't want.

pystache can do that by passing a lambda that does nothing to the escape parameter of the Renderer. Not sure how to do that with chevron, it sounds like boolean escape=False, defaulting to True would do it.

**Comment by dcmoore-gd** [comment]
Have you tried using triple braces `{{{...}}}`?

**Comment by bsergean** [comment]
I did not. Let me try it.

Is that a standard mustache syntax ?

**Comment by bsergean** [comment]
Just found that in the spec. Thanks !
All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

**Comment by bsergean** [comment]
Works great / I was using pystache but I'm now using chevron. Thanks for the tip !

**Comment by dcmoore-gd** [comment]
You're welcome!
