### ISSUE TITLE
HTML tags problem

### ISSUE THREAD

**Issue by nclsbayona** [noahmorrison/chevron#98]
I create this issue because I'm facing a problem when trying to generate an HTML table from python. I'm using the prettytable module, specifically get_html_string() method, and I see that maybe the render function needs a way of just replacing the text with the plain text. I think that this can be accomplished by adding a parameter for the coding options.
In python I get the following table
```text
<table>        <thead>            <tr>                <th>OS name</th>                <th>Time spent</th>            </tr>        </thead>        <tbody>            <tr>                <td>Linux</td>                <td>37 hours and 57 minutes</td>            </tr>        </tbody>    </table>
```
However, in HTML it looks like this
```html
&lt;table&gt;        &lt;thead&gt;            &lt;tr&gt;                &lt;th&gt;OS name&lt;/th&gt;                &lt;th&gt;Time spent&lt;/th&gt;            &lt;/tr&gt;        &lt;/thead&gt;        &lt;tbody&gt;            &lt;tr&gt;                &lt;td&gt;Linux&lt;/td&gt;                &lt;td&gt;37 hours and 57 minutes&lt;/td&gt;            &lt;/tr&gt;        &lt;/tbody&gt;    &lt;/table&gt;
```

**Comment by jscaria** [comment]
Take a look at https://stackoverflow.com/a/15262481.

**Comment by nclsbayona** [comment]
Ok. Thanks

**Comment by nclsbayona** [comment]
Thanks a lot @jscaria , we can close this now
